services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"

  client-gateway:
    build: ./client-gateway
    ports:
      - "${CLIENT_GATEWAY_PORT}:3000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222
    develop:
      watch:
        - action: sync
          path: ./client-gateway/src
          target: /usr/src/app/src

  products-microservice:
    build: ./products
    ports:
      - "3001:3001"
    volumes:
      - ./products/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
    develop:
      watch:
        - action: sync
          path: ./products/src
          target: /usr/src/app/src

  orders:
    depends_on:
      orders-db:
        condition: service_healthy
    build: ./orders
    ports:
      - "3002:3002"
    volumes:
      - ./orders/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/orders_db?schema=public
    develop:
      watch:
        - action: sync
          path: ./orders/src
          target: /usr/src/app/src

  orders-db:
    container_name: orders-database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: orders_db
    ports:
      - "5432:5432"
    volumes:
      - ./orders/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  payments:
    container_name: payments-microservice
    build: ./payments
    ports:
      - "${PAYMENTS_MS_PORT}:${PAYMENTS_MS_PORT}"
    volumes:
      - ./payments/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=${PAYMENTS_MS_PORT}
      - NATS_SERVERS=nats://nats-server:4222
      - STRIPE_SECRET=${STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
    develop:
      watch:
        - action: sync
          path: ./payments/src
          target: /usr/src/app/src
